const alpha2CountryCodes = new Map();

alpha2CountryCodes.set("AF", "Afghanistan");
alpha2CountryCodes.set("AL", "Albania");
alpha2CountryCodes.set("DZ", "Algeria");
alpha2CountryCodes.set("AS", "American Samoa");
alpha2CountryCodes.set("AD", "Andorra");
alpha2CountryCodes.set("AO", "Angola");
alpha2CountryCodes.set("AI", "Anguilla");
alpha2CountryCodes.set("AQ", "Antarctica");
alpha2CountryCodes.set("AG", "Antigua and Barbuda");
alpha2CountryCodes.set("AR", "Argentina");
alpha2CountryCodes.set("AM", "Armenia");
alpha2CountryCodes.set("AW", "Aruba");
alpha2CountryCodes.set("AU", "Australia");
alpha2CountryCodes.set("AT", "Austria");
alpha2CountryCodes.set("AZ", "Azerbaijan");
alpha2CountryCodes.set("BS", "Bahamas (the)");
alpha2CountryCodes.set("BH", "Bahrain");
alpha2CountryCodes.set("BD", "Bangladesh");
alpha2CountryCodes.set("BB", "Barbados");
alpha2CountryCodes.set("BY", "Belarus");
alpha2CountryCodes.set("BE", "Belgium");
alpha2CountryCodes.set("BZ", "Belize");
alpha2CountryCodes.set("BJ", "Benin");
alpha2CountryCodes.set("BM", "Bermuda");
alpha2CountryCodes.set("BT", "Bhutan");
alpha2CountryCodes.set("BO", "Bolivia (Plurinational State of)");
alpha2CountryCodes.set("BQ", "Bonaire, Sint Eustatius and Saba");
alpha2CountryCodes.set("BA", "Bosnia and Herzegovina");
alpha2CountryCodes.set("BW", "Botswana");
alpha2CountryCodes.set("BV", "Bouvet Island");
alpha2CountryCodes.set("BR", "Brazil");
alpha2CountryCodes.set("IO", "British Indian Ocean Territory (the)");
alpha2CountryCodes.set("BN", "Brunei Darussalam");
alpha2CountryCodes.set("BG", "Bulgaria");
alpha2CountryCodes.set("BF", "Burkina Faso");
alpha2CountryCodes.set("BI", "Burundi");
alpha2CountryCodes.set("CV", "Cabo Verde");
alpha2CountryCodes.set("KH", "Cambodia");
alpha2CountryCodes.set("CM", "Cameroon");
alpha2CountryCodes.set("CA", "Canada");
alpha2CountryCodes.set("KY", "Cayman Islands (the)");
alpha2CountryCodes.set("CF", "Central African Republic (the)");
alpha2CountryCodes.set("TD", "Chad");
alpha2CountryCodes.set("CL", "Chile");
alpha2CountryCodes.set("CN", "China");
alpha2CountryCodes.set("CX", "Christmas Island");
alpha2CountryCodes.set("CC", "Cocos (Keeling) Islands (the)");
alpha2CountryCodes.set("CO", "Colombia");
alpha2CountryCodes.set("KM", "Comoros (the)");
alpha2CountryCodes.set("CD", "Congo (the Democratic Republic of the)");
alpha2CountryCodes.set("CG", "Congo (the)");
alpha2CountryCodes.set("CK", "Cook Islands (the)");
alpha2CountryCodes.set("CR", "Costa Rica");
alpha2CountryCodes.set("HR", "Croatia");
alpha2CountryCodes.set("CU", "Cuba");
alpha2CountryCodes.set("CW", "Curaçao");
alpha2CountryCodes.set("CY", "Cyprus");
alpha2CountryCodes.set("CZ", "Czechia");
alpha2CountryCodes.set("CI", "Côte d'Ivoire");
alpha2CountryCodes.set("DK", "Denmark");
alpha2CountryCodes.set("DJ", "Djibouti");
alpha2CountryCodes.set("DM", "Dominica");
alpha2CountryCodes.set("DO", "Dominican Republic (the)");
alpha2CountryCodes.set("EC", "Ecuador");
alpha2CountryCodes.set("EG", "Egypt");
alpha2CountryCodes.set("SV", "El Salvador");
alpha2CountryCodes.set("GQ", "Equatorial Guinea");
alpha2CountryCodes.set("ER", "Eritrea");
alpha2CountryCodes.set("EE", "Estonia");
alpha2CountryCodes.set("SZ", "Eswatini");
alpha2CountryCodes.set("ET", "Ethiopia");
alpha2CountryCodes.set("FK", "Falkland Islands (the) [Malvinas]");
alpha2CountryCodes.set("FO", "Faroe Islands (the)");
alpha2CountryCodes.set("FJ", "Fiji");
alpha2CountryCodes.set("FI", "Finland");
alpha2CountryCodes.set("FR", "France");
alpha2CountryCodes.set("GF", "French Guiana");
alpha2CountryCodes.set("PF", "French Polynesia");
alpha2CountryCodes.set("TF", "French Southern Territories (the)");
alpha2CountryCodes.set("GA", "Gabon");
alpha2CountryCodes.set("GM", "Gambia (the)");
alpha2CountryCodes.set("GE", "Georgia");
alpha2CountryCodes.set("DE", "Germany");
alpha2CountryCodes.set("GH", "Ghana");
alpha2CountryCodes.set("GI", "Gibraltar");
alpha2CountryCodes.set("GR", "Greece");
alpha2CountryCodes.set("GL", "Greenland");
alpha2CountryCodes.set("GD", "Grenada");
alpha2CountryCodes.set("GP", "Guadeloupe");
alpha2CountryCodes.set("GU", "Guam");
alpha2CountryCodes.set("GT", "Guatemala");
alpha2CountryCodes.set("GG", "Guernsey");
alpha2CountryCodes.set("GN", "Guinea");
alpha2CountryCodes.set("GW", "Guinea-Bissau");
alpha2CountryCodes.set("GY", "Guyana");
alpha2CountryCodes.set("HT", "Haiti");
alpha2CountryCodes.set("HM", "Heard Island and McDonald Islands");
alpha2CountryCodes.set("VA", "Holy See (the)");
alpha2CountryCodes.set("HN", "Honduras");
alpha2CountryCodes.set("HK", "Hong Kong");
alpha2CountryCodes.set("HU", "Hungary");
alpha2CountryCodes.set("IS", "Iceland");
alpha2CountryCodes.set("IN", "India");
alpha2CountryCodes.set("ID", "Indonesia");
alpha2CountryCodes.set("IR", "Iran (Islamic Republic of)");
alpha2CountryCodes.set("IQ", "Iraq");
alpha2CountryCodes.set("IE", "Ireland");
alpha2CountryCodes.set("IM", "Isle of Man");
alpha2CountryCodes.set("IL", "Israel");
alpha2CountryCodes.set("IT", "Italy");
alpha2CountryCodes.set("JM", "Jamaica");
alpha2CountryCodes.set("JP", "Japan");
alpha2CountryCodes.set("JE", "Jersey");
alpha2CountryCodes.set("JO", "Jordan");
alpha2CountryCodes.set("KZ", "Kazakhstan");
alpha2CountryCodes.set("KE", "Kenya");
alpha2CountryCodes.set("KI", "Kiribati");
alpha2CountryCodes.set("KP", "Korea (the Democratic People's Republic of)");
alpha2CountryCodes.set("KR", "Korea (the Republic of)");
alpha2CountryCodes.set("KW", "Kuwait");
alpha2CountryCodes.set("KG", "Kyrgyzstan");
alpha2CountryCodes.set("LA", "Lao People's Democratic Republic (the)");
alpha2CountryCodes.set("LV", "Latvia");
alpha2CountryCodes.set("LB", "Lebanon");
alpha2CountryCodes.set("LS", "Lesotho");
alpha2CountryCodes.set("LR", "Liberia");
alpha2CountryCodes.set("LY", "Libya");
alpha2CountryCodes.set("LI", "Liechtenstein");
alpha2CountryCodes.set("LT", "Lithuania");
alpha2CountryCodes.set("LU", "Luxembourg");
alpha2CountryCodes.set("MO", "Macao");
alpha2CountryCodes.set("MG", "Madagascar");
alpha2CountryCodes.set("MW", "Malawi");
alpha2CountryCodes.set("MY", "Malaysia");
alpha2CountryCodes.set("MV", "Maldives");
alpha2CountryCodes.set("ML", "Mali");
alpha2CountryCodes.set("MT", "Malta");
alpha2CountryCodes.set("MH", "Marshall Islands (the)");
alpha2CountryCodes.set("MQ", "Martinique");
alpha2CountryCodes.set("MR", "Mauritania");
alpha2CountryCodes.set("MU", "Mauritius");
alpha2CountryCodes.set("YT", "Mayotte");
alpha2CountryCodes.set("MX", "Mexico");
alpha2CountryCodes.set("FM", "Micronesia (Federated States of)");
alpha2CountryCodes.set("MD", "Moldova (the Republic of)");
alpha2CountryCodes.set("MC", "Monaco");
alpha2CountryCodes.set("MN", "Mongolia");
alpha2CountryCodes.set("ME", "Montenegro");
alpha2CountryCodes.set("MS", "Montserrat");
alpha2CountryCodes.set("MA", "Morocco");
alpha2CountryCodes.set("MZ", "Mozambique");
alpha2CountryCodes.set("MM", "Myanmar");
alpha2CountryCodes.set("NA", "Namibia");
alpha2CountryCodes.set("NR", "Nauru");
alpha2CountryCodes.set("NP", "Nepal");
alpha2CountryCodes.set("NL", "Netherlands (the)");
alpha2CountryCodes.set("NC", "New Caledonia");
alpha2CountryCodes.set("NZ", "New Zealand");
alpha2CountryCodes.set("NI", "Nicaragua");
alpha2CountryCodes.set("NE", "Niger (the)");
alpha2CountryCodes.set("NG", "Nigeria");
alpha2CountryCodes.set("NU", "Niue");
alpha2CountryCodes.set("NF", "Norfolk Island");
alpha2CountryCodes.set("MP", "Northern Mariana Islands (the)");
alpha2CountryCodes.set("NO", "Norway");
alpha2CountryCodes.set("OM", "Oman");
alpha2CountryCodes.set("PK", "Pakistan");
alpha2CountryCodes.set("PW", "Palau");
alpha2CountryCodes.set("PS", "Palestine, State of");
alpha2CountryCodes.set("PA", "Panama");
alpha2CountryCodes.set("PG", "Papua New Guinea");
alpha2CountryCodes.set("PY", "Paraguay");
alpha2CountryCodes.set("PE", "Peru");
alpha2CountryCodes.set("PH", "Philippines (the)");
alpha2CountryCodes.set("PN", "Pitcairn");
alpha2CountryCodes.set("PL", "Poland");
alpha2CountryCodes.set("PT", "Portugal");
alpha2CountryCodes.set("PR", "Puerto Rico");
alpha2CountryCodes.set("QA", "Qatar");
alpha2CountryCodes.set("MK", "Republic of North Macedonia");
alpha2CountryCodes.set("RO", "Romania");
alpha2CountryCodes.set("RU", "Russian Federation (the)");
alpha2CountryCodes.set("RW", "Rwanda");
alpha2CountryCodes.set("RE", "Réunion");
alpha2CountryCodes.set("BL", "Saint Barthélemy");
alpha2CountryCodes.set("SH", "Saint Helena, Ascension and Tristan da Cunha");
alpha2CountryCodes.set("KN", "Saint Kitts and Nevis");
alpha2CountryCodes.set("LC", "Saint Lucia");
alpha2CountryCodes.set("MF", "Saint Martin (French part)");
alpha2CountryCodes.set("PM", "Saint Pierre and Miquelon");
alpha2CountryCodes.set("VC", "Saint Vincent and the Grenadines");
alpha2CountryCodes.set("WS", "Samoa");
alpha2CountryCodes.set("SM", "San Marino");
alpha2CountryCodes.set("ST", "Sao Tome and Principe");
alpha2CountryCodes.set("SA", "Saudi Arabia");
alpha2CountryCodes.set("SN", "Senegal");
alpha2CountryCodes.set("RS", "Serbia");
alpha2CountryCodes.set("SC", "Seychelles");
alpha2CountryCodes.set("SL", "Sierra Leone");
alpha2CountryCodes.set("SG", "Singapore");
alpha2CountryCodes.set("SX", "Sint Maarten (Dutch part)");
alpha2CountryCodes.set("SK", "Slovakia");
alpha2CountryCodes.set("SI", "Slovenia");
alpha2CountryCodes.set("SB", "Solomon Islands");
alpha2CountryCodes.set("SO", "Somalia");
alpha2CountryCodes.set("ZA", "South Africa");
alpha2CountryCodes.set("GS", "South Georgia and the South Sandwich Islands");
alpha2CountryCodes.set("SS", "South Sudan");
alpha2CountryCodes.set("ES", "Spain");
alpha2CountryCodes.set("LK", "Sri Lanka");
alpha2CountryCodes.set("SD", "Sudan (the)");
alpha2CountryCodes.set("SR", "Suriname");
alpha2CountryCodes.set("SJ", "Svalbard and Jan Mayen");
alpha2CountryCodes.set("SE", "Sweden");
alpha2CountryCodes.set("CH", "Switzerland");
alpha2CountryCodes.set("SY", "Syrian Arab Republic");
alpha2CountryCodes.set("TW", "Taiwan (Province of China)");
alpha2CountryCodes.set("TJ", "Tajikistan");
alpha2CountryCodes.set("TZ", "Tanzania, United Republic of");
alpha2CountryCodes.set("TH", "Thailand");
alpha2CountryCodes.set("TL", "Timor-Leste");
alpha2CountryCodes.set("TG", "Togo");
alpha2CountryCodes.set("TK", "Tokelau");
alpha2CountryCodes.set("TO", "Tonga");
alpha2CountryCodes.set("TT", "Trinidad and Tobago");
alpha2CountryCodes.set("TN", "Tunisia");
alpha2CountryCodes.set("TR", "Turkey");
alpha2CountryCodes.set("TM", "Turkmenistan");
alpha2CountryCodes.set("TC", "Turks and Caicos Islands (the)");
alpha2CountryCodes.set("TV", "Tuvalu");
alpha2CountryCodes.set("UG", "Uganda");
alpha2CountryCodes.set("UA", "Ukraine");
alpha2CountryCodes.set("AE", "United Arab Emirates (the)");
alpha2CountryCodes.set(
  "GB",
  "United Kingdom of Great Britain and Northern Ireland (the)"
);
alpha2CountryCodes.set("UM", "United States Minor Outlying Islands (the)");
alpha2CountryCodes.set("US", "United States of America (the)");
alpha2CountryCodes.set("UY", "Uruguay");
alpha2CountryCodes.set("UZ", "Uzbekistan");
alpha2CountryCodes.set("VU", "Vanuatu");
alpha2CountryCodes.set("VE", "Venezuela (Bolivarian Republic of)");
alpha2CountryCodes.set("VN", "Viet Nam");
alpha2CountryCodes.set("VG", "Virgin Islands (British)");
alpha2CountryCodes.set("VI", "Virgin Islands (U.S.)");
alpha2CountryCodes.set("WF", "Wallis and Futuna");
alpha2CountryCodes.set("EH", "Western Sahara");
alpha2CountryCodes.set("YE", "Yemen");
alpha2CountryCodes.set("ZM", "Zambia");
alpha2CountryCodes.set("ZW", "Zimbabwe");
alpha2CountryCodes.set("AX", "Åland Islands");
