const alpha3CountryCodes = new Map();

alpha3CountryCodes.set("AFG", "Afghanistan");
alpha3CountryCodes.set("ALB", "Albania");
alpha3CountryCodes.set("DZA", "Algeria");
alpha3CountryCodes.set("ASM", "American Samoa");
alpha3CountryCodes.set("AND", "Andorra");
alpha3CountryCodes.set("AGO", "Angola");
alpha3CountryCodes.set("AIA", "Anguilla");
alpha3CountryCodes.set("ATA", "Antarctica");
alpha3CountryCodes.set("ATG", "Antigua and Barbuda");
alpha3CountryCodes.set("ARG", "Argentina");
alpha3CountryCodes.set("ARM", "Armenia");
alpha3CountryCodes.set("ABW", "Aruba");
alpha3CountryCodes.set("AUS", "Australia");
alpha3CountryCodes.set("AUT", "Austria");
alpha3CountryCodes.set("AZE", "Azerbaijan");
alpha3CountryCodes.set("BHS", "Bahamas (the)");
alpha3CountryCodes.set("BHR", "Bahrain");
alpha3CountryCodes.set("BGD", "Bangladesh");
alpha3CountryCodes.set("BRB", "Barbados");
alpha3CountryCodes.set("BLR", "Belarus");
alpha3CountryCodes.set("BEL", "Belgium");
alpha3CountryCodes.set("BLZ", "Belize");
alpha3CountryCodes.set("BEN", "Benin");
alpha3CountryCodes.set("BMU", "Bermuda");
alpha3CountryCodes.set("BTN", "Bhutan");
alpha3CountryCodes.set("BOL", "Bolivia (Plurinational State of)");
alpha3CountryCodes.set("BES", "Bonaire, Sint Eustatius and Saba");
alpha3CountryCodes.set("BIH", "Bosnia and Herzegovina");
alpha3CountryCodes.set("BWA", "Botswana");
alpha3CountryCodes.set("BVT", "Bouvet Island");
alpha3CountryCodes.set("BRA", "Brazil");
alpha3CountryCodes.set("IOT", "British Indian Ocean Territory (the)");
alpha3CountryCodes.set("BRN", "Brunei Darussalam");
alpha3CountryCodes.set("BGR", "Bulgaria");
alpha3CountryCodes.set("BFA", "Burkina Faso");
alpha3CountryCodes.set("BDI", "Burundi");
alpha3CountryCodes.set("CPV", "Cabo Verde");
alpha3CountryCodes.set("KHM", "Cambodia");
alpha3CountryCodes.set("CMR", "Cameroon");
alpha3CountryCodes.set("CAN", "Canada");
alpha3CountryCodes.set("CYM", "Cayman Islands (the)");
alpha3CountryCodes.set("CAF", "Central African Republic (the)");
alpha3CountryCodes.set("TCD", "Chad");
alpha3CountryCodes.set("CHL", "Chile");
alpha3CountryCodes.set("CHN", "China");
alpha3CountryCodes.set("CXR", "Christmas Island");
alpha3CountryCodes.set("CCK", "Cocos (Keeling) Islands (the)");
alpha3CountryCodes.set("COL", "Colombia");
alpha3CountryCodes.set("COM", "Comoros (the)");
alpha3CountryCodes.set("COD", "Congo (the Democratic Republic of the)");
alpha3CountryCodes.set("COG", "Congo (the)");
alpha3CountryCodes.set("COK", "Cook Islands (the)");
alpha3CountryCodes.set("CRI", "Costa Rica");
alpha3CountryCodes.set("HRV", "Croatia");
alpha3CountryCodes.set("CUB", "Cuba");
alpha3CountryCodes.set("CUW", "Curaçao");
alpha3CountryCodes.set("CYP", "Cyprus");
alpha3CountryCodes.set("CZE", "Czechia");
alpha3CountryCodes.set("CIV", "Côte d'Ivoire");
alpha3CountryCodes.set("DNK", "Denmark");
alpha3CountryCodes.set("DJI", "Djibouti");
alpha3CountryCodes.set("DMA", "Dominica");
alpha3CountryCodes.set("DOM", "Dominican Republic (the)");
alpha3CountryCodes.set("ECU", "Ecuador");
alpha3CountryCodes.set("EGY", "Egypt");
alpha3CountryCodes.set("SLV", "El Salvador");
alpha3CountryCodes.set("GNQ", "Equatorial Guinea");
alpha3CountryCodes.set("ERI", "Eritrea");
alpha3CountryCodes.set("EST", "Estonia");
alpha3CountryCodes.set("SWZ", "Eswatini");
alpha3CountryCodes.set("ETH", "Ethiopia");
alpha3CountryCodes.set("FLK", "Falkland Islands (the) [Malvinas]");
alpha3CountryCodes.set("FRO", "Faroe Islands (the)");
alpha3CountryCodes.set("FJI", "Fiji");
alpha3CountryCodes.set("FIN", "Finland");
alpha3CountryCodes.set("FRA", "France");
alpha3CountryCodes.set("GUF", "French Guiana");
alpha3CountryCodes.set("PYF", "French Polynesia");
alpha3CountryCodes.set("ATF", "French Southern Territories (the)");
alpha3CountryCodes.set("GAB", "Gabon");
alpha3CountryCodes.set("GMB", "Gambia (the)");
alpha3CountryCodes.set("GEO", "Georgia");
alpha3CountryCodes.set("DEU", "Germany");
alpha3CountryCodes.set("GHA", "Ghana");
alpha3CountryCodes.set("GIB", "Gibraltar");
alpha3CountryCodes.set("GRC", "Greece");
alpha3CountryCodes.set("GRL", "Greenland");
alpha3CountryCodes.set("GRD", "Grenada");
alpha3CountryCodes.set("GLP", "Guadeloupe");
alpha3CountryCodes.set("GUM", "Guam");
alpha3CountryCodes.set("GTM", "Guatemala");
alpha3CountryCodes.set("GGY", "Guernsey");
alpha3CountryCodes.set("GIN", "Guinea");
alpha3CountryCodes.set("GNB", "Guinea-Bissau");
alpha3CountryCodes.set("GUY", "Guyana");
alpha3CountryCodes.set("HTI", "Haiti");
alpha3CountryCodes.set("HMD", "Heard Island and McDonald Islands");
alpha3CountryCodes.set("VAT", "Holy See (the)");
alpha3CountryCodes.set("HND", "Honduras");
alpha3CountryCodes.set("HKG", "Hong Kong");
alpha3CountryCodes.set("HUN", "Hungary");
alpha3CountryCodes.set("ISL", "Iceland");
alpha3CountryCodes.set("IND", "India");
alpha3CountryCodes.set("IDN", "Indonesia");
alpha3CountryCodes.set("IRN", "Iran (Islamic Republic of)");
alpha3CountryCodes.set("IRQ", "Iraq");
alpha3CountryCodes.set("IRL", "Ireland");
alpha3CountryCodes.set("IMN", "Isle of Man");
alpha3CountryCodes.set("ISR", "Israel");
alpha3CountryCodes.set("ITA", "Italy");
alpha3CountryCodes.set("JAM", "Jamaica");
alpha3CountryCodes.set("JPN", "Japan");
alpha3CountryCodes.set("JEY", "Jersey");
alpha3CountryCodes.set("JOR", "Jordan");
alpha3CountryCodes.set("KAZ", "Kazakhstan");
alpha3CountryCodes.set("KEN", "Kenya");
alpha3CountryCodes.set("KIR", "Kiribati");
alpha3CountryCodes.set("PRK", "Korea (the Democratic People's Republic of)");
alpha3CountryCodes.set("KOR", "Korea (the Republic of)");
alpha3CountryCodes.set("KWT", "Kuwait");
alpha3CountryCodes.set("KGZ", "Kyrgyzstan");
alpha3CountryCodes.set("LAO", "Lao People's Democratic Republic (the)");
alpha3CountryCodes.set("LVA", "Latvia");
alpha3CountryCodes.set("LBN", "Lebanon");
alpha3CountryCodes.set("LSO", "Lesotho");
alpha3CountryCodes.set("LBR", "Liberia");
alpha3CountryCodes.set("LBY", "Libya");
alpha3CountryCodes.set("LIE", "Liechtenstein");
alpha3CountryCodes.set("LTU", "Lithuania");
alpha3CountryCodes.set("LUX", "Luxembourg");
alpha3CountryCodes.set("MAC", "Macao");
alpha3CountryCodes.set("MDG", "Madagascar");
alpha3CountryCodes.set("MWI", "Malawi");
alpha3CountryCodes.set("MYS", "Malaysia");
alpha3CountryCodes.set("MDV", "Maldives");
alpha3CountryCodes.set("MLI", "Mali");
alpha3CountryCodes.set("MLT", "Malta");
alpha3CountryCodes.set("MHL", "Marshall Islands (the)");
alpha3CountryCodes.set("MTQ", "Martinique");
alpha3CountryCodes.set("MRT", "Mauritania");
alpha3CountryCodes.set("MUS", "Mauritius");
alpha3CountryCodes.set("MYT", "Mayotte");
alpha3CountryCodes.set("MEX", "Mexico");
alpha3CountryCodes.set("FSM", "Micronesia (Federated States of)");
alpha3CountryCodes.set("MDA", "Moldova (the Republic of)");
alpha3CountryCodes.set("MCO", "Monaco");
alpha3CountryCodes.set("MNG", "Mongolia");
alpha3CountryCodes.set("MNE", "Montenegro");
alpha3CountryCodes.set("MSR", "Montserrat");
alpha3CountryCodes.set("MAR", "Morocco");
alpha3CountryCodes.set("MOZ", "Mozambique");
alpha3CountryCodes.set("MMR", "Myanmar");
alpha3CountryCodes.set("NAM", "Namibia");
alpha3CountryCodes.set("NRU", "Nauru");
alpha3CountryCodes.set("NPL", "Nepal");
alpha3CountryCodes.set("NLD", "Netherlands (the)");
alpha3CountryCodes.set("NCL", "New Caledonia");
alpha3CountryCodes.set("NZL", "New Zealand");
alpha3CountryCodes.set("NIC", "Nicaragua");
alpha3CountryCodes.set("NER", "Niger (the)");
alpha3CountryCodes.set("NGA", "Nigeria");
alpha3CountryCodes.set("NIU", "Niue");
alpha3CountryCodes.set("NFK", "Norfolk Island");
alpha3CountryCodes.set("MNP", "Northern Mariana Islands (the)");
alpha3CountryCodes.set("NOR", "Norway");
alpha3CountryCodes.set("OMN", "Oman");
alpha3CountryCodes.set("PAK", "Pakistan");
alpha3CountryCodes.set("PLW", "Palau");
alpha3CountryCodes.set("PSE", "Palestine, State of");
alpha3CountryCodes.set("PAN", "Panama");
alpha3CountryCodes.set("PNG", "Papua New Guinea");
alpha3CountryCodes.set("PRY", "Paraguay");
alpha3CountryCodes.set("PER", "Peru");
alpha3CountryCodes.set("PHL", "Philippines (the)");
alpha3CountryCodes.set("PCN", "Pitcairn");
alpha3CountryCodes.set("POL", "Poland");
alpha3CountryCodes.set("PRT", "Portugal");
alpha3CountryCodes.set("PRI", "Puerto Rico");
alpha3CountryCodes.set("QAT", "Qatar");
alpha3CountryCodes.set("MKD", "Republic of North Macedonia");
alpha3CountryCodes.set("ROU", "Romania");
alpha3CountryCodes.set("RUS", "Russian Federation (the)");
alpha3CountryCodes.set("RWA", "Rwanda");
alpha3CountryCodes.set("REU", "Réunion");
alpha3CountryCodes.set("BLM", "Saint Barthélemy");
alpha3CountryCodes.set("SHN", "Saint Helena, Ascension and Tristan da Cunha");
alpha3CountryCodes.set("KNA", "Saint Kitts and Nevis");
alpha3CountryCodes.set("LCA", "Saint Lucia");
alpha3CountryCodes.set("MAF", "Saint Martin (French part)");
alpha3CountryCodes.set("SPM", "Saint Pierre and Miquelon");
alpha3CountryCodes.set("VCT", "Saint Vincent and the Grenadines");
alpha3CountryCodes.set("WSM", "Samoa");
alpha3CountryCodes.set("SMR", "San Marino");
alpha3CountryCodes.set("STP", "Sao Tome and Principe");
alpha3CountryCodes.set("SAU", "Saudi Arabia");
alpha3CountryCodes.set("SEN", "Senegal");
alpha3CountryCodes.set("SRB", "Serbia");
alpha3CountryCodes.set("SYC", "Seychelles");
alpha3CountryCodes.set("SLE", "Sierra Leone");
alpha3CountryCodes.set("SGP", "Singapore");
alpha3CountryCodes.set("SXM", "Sint Maarten (Dutch part)");
alpha3CountryCodes.set("SVK", "Slovakia");
alpha3CountryCodes.set("SVN", "Slovenia");
alpha3CountryCodes.set("SLB", "Solomon Islands");
alpha3CountryCodes.set("SOM", "Somalia");
alpha3CountryCodes.set("ZAF", "South Africa");
alpha3CountryCodes.set("SGS", "South Georgia and the South Sandwich Islands");
alpha3CountryCodes.set("SSD", "South Sudan");
alpha3CountryCodes.set("ESP", "Spain");
alpha3CountryCodes.set("LKA", "Sri Lanka");
alpha3CountryCodes.set("SDN", "Sudan (the)");
alpha3CountryCodes.set("SUR", "Suriname");
alpha3CountryCodes.set("SJM", "Svalbard and Jan Mayen");
alpha3CountryCodes.set("SWE", "Sweden");
alpha3CountryCodes.set("CHE", "Switzerland");
alpha3CountryCodes.set("SYR", "Syrian Arab Republic");
alpha3CountryCodes.set("TWN", "Taiwan (Province of China)");
alpha3CountryCodes.set("TJK", "Tajikistan");
alpha3CountryCodes.set("TZA", "Tanzania, United Republic of");
alpha3CountryCodes.set("THA", "Thailand");
alpha3CountryCodes.set("TLS", "Timor-Leste");
alpha3CountryCodes.set("TGO", "Togo");
alpha3CountryCodes.set("TKL", "Tokelau");
alpha3CountryCodes.set("TON", "Tonga");
alpha3CountryCodes.set("TTO", "Trinidad and Tobago");
alpha3CountryCodes.set("TUN", "Tunisia");
alpha3CountryCodes.set("TUR", "Turkey");
alpha3CountryCodes.set("TKM", "Turkmenistan");
alpha3CountryCodes.set("TCA", "Turks and Caicos Islands (the)");
alpha3CountryCodes.set("TUV", "Tuvalu");
alpha3CountryCodes.set("UGA", "Uganda");
alpha3CountryCodes.set("UKR", "Ukraine");
alpha3CountryCodes.set("ARE", "United Arab Emirates (the)");
alpha3CountryCodes.set(
  "GBR",
  "United Kingdom of Great Britain and Northern Ireland (the)"
);
alpha3CountryCodes.set("UMI", "United States Minor Outlying Islands (the)");
alpha3CountryCodes.set("USA", "United States of America (the)");
alpha3CountryCodes.set("URY", "Uruguay");
alpha3CountryCodes.set("UZB", "Uzbekistan");
alpha3CountryCodes.set("VUT", "Vanuatu");
alpha3CountryCodes.set("VEN", "Venezuela (Bolivarian Republic of)");
alpha3CountryCodes.set("VNM", "Viet Nam");
alpha3CountryCodes.set("VGB", "Virgin Islands (British)");
alpha3CountryCodes.set("VIR", "Virgin Islands (U.S.)");
alpha3CountryCodes.set("WLF", "Wallis and Futuna");
alpha3CountryCodes.set("ESH", "Western Sahara");
alpha3CountryCodes.set("YEM", "Yemen");
alpha3CountryCodes.set("ZMB", "Zambia");
alpha3CountryCodes.set("ZWE", "Zimbabwe");
alpha3CountryCodes.set("ALA", "Åland Islands");
