const MEDICINAL_PRODUCT_NAMES = new Map();
MEDICINAL_PRODUCT_NAMES.set("XM68M6", "COVID-19 vaccine");
MEDICINAL_PRODUCT_NAMES.set("XM1NL1", "COVID-19 vaccine, inactivated virus");
MEDICINAL_PRODUCT_NAMES.set("XM7HT3", "CoronaVac®");
MEDICINAL_PRODUCT_NAMES.set("XM8866", "BBIBP-CorV");
MEDICINAL_PRODUCT_NAMES.set("XM9TQ1", "KCONVAC");
MEDICINAL_PRODUCT_NAMES.set("XM1G90", "Covaxin");
MEDICINAL_PRODUCT_NAMES.set("XM85P5", "Covi-Vac");
MEDICINAL_PRODUCT_NAMES.set("XM9FQ7", "Hayat-Vax");
MEDICINAL_PRODUCT_NAMES.set("XM97N6", "QazVac");
MEDICINAL_PRODUCT_NAMES.set("XM2YG8", "COVIran Barakat");
MEDICINAL_PRODUCT_NAMES.set("XM3U61", "Inactivated SARS-CoV-2 vaccine");
MEDICINAL_PRODUCT_NAMES.set(
  "XM5DF6",
  "COVID-19 vaccine, live attenuated virus"
);
MEDICINAL_PRODUCT_NAMES.set(
  "XM9QW8",
  "COVID-19 vaccine, non-replicating viral vector"
);
MEDICINAL_PRODUCT_NAMES.set("XM4YL8", "COVID-19 Vaccine AstraZeneca");
MEDICINAL_PRODUCT_NAMES.set("XM97T2", "Covishield®");
MEDICINAL_PRODUCT_NAMES.set("XM6QV1", "COVID-19 Vaccine Janssen");
MEDICINAL_PRODUCT_NAMES.set("XM1AG7", "Convidecia");
MEDICINAL_PRODUCT_NAMES.set("XM5ZJ4", "Gam-Covid-Vac");
MEDICINAL_PRODUCT_NAMES.set("XM5QM6", "Sputnik-Light");
MEDICINAL_PRODUCT_NAMES.set(
  "XM0CX4",
  "COVID-19 vaccine, replicating viral vector"
);
MEDICINAL_PRODUCT_NAMES.set(
  "XM5JC5",
  "COVID-19 vaccine, virus protein subunit"
);
MEDICINAL_PRODUCT_NAMES.set("XM3CT4", "Recombinant SARS-CoV-2 vaccine");
MEDICINAL_PRODUCT_NAMES.set("XM3PG0", "Soberana-02");
MEDICINAL_PRODUCT_NAMES.set("XM4EC8", "MVC-COV1901");
MEDICINAL_PRODUCT_NAMES.set("XM6SZ8", "EpiVacCorona");
MEDICINAL_PRODUCT_NAMES.set(
  "XM1J92",
  "COVID-19 vaccine, virus like particle (VLP)"
);
MEDICINAL_PRODUCT_NAMES.set("XM6AT1", "COVID-19 vaccine, DNA based");
MEDICINAL_PRODUCT_NAMES.set("XM52P3", "ZyCov-D");
MEDICINAL_PRODUCT_NAMES.set("XM0GQ8", "COVID-19 vaccine, RNA based");
MEDICINAL_PRODUCT_NAMES.set("XM8NQ0", "Comirnaty®");
MEDICINAL_PRODUCT_NAMES.set("XM3DT5", "COVID-19 Vaccine Moderna");
